
PLOT_BLUE = '#7eb0d5'
PLOT_PINK = '#fdcce5'
PLOT_RED = '#fd7f6f'
PLOT_ORANGE = '#ffb55a'
PLOT_PURPLE = '#bd7ebe'
PLOT_LIGHT_PURPLE = '#beb9db'
PLOT_YELLOW = '#ffee65'
PLOT_GREEN = '#b2e061'
PLOT_CYAN = '#8bd3c7'

LINE_WIDTH_SMALL = 2
LINE_WIDTH_NORMAL = 4
LINE_WIDTH_MEDIUM = 6
LINE_WIDTH_BIG = 8

FONT_SIZE_EXTRA_SMALL = 8
FONT_SIZE_SMALL = 10
FONT_SIZE_NORMAL = 12
FONT_SIZE_MEDIUM = 14
FONT_SIZE_BIG = 16

from plot.plot import *
